name: Remove Stack

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "[ON RUNNER] Set project variables"
        run: |
          projectname="${{ github.event.repository.name }}"
          echo "project_name=$projectname" >> $GITHUB_ENV
          echo "project_folder=/home/${{ secrets.DEPLOY_USERNAME }}/$projectname" >> $GITHUB_ENV
      
      - name: "[ON HOST] Remove Stack"
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_SSHKEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            cd ${{ env.project_folder }}
            docker compose --env-file .env down
            cd ..
            rm -rf ${{ env.project_folder }}
